language: node_js
sudo: true
node_js:
  - "node"
  - "8"
  - "6"
  - "4"
before_install:
  - npm install -g npm@latest
before_script:
  - chmod -R 777 ./project/build/integration
env:
  global:
    - DOCKER_INTEGRATION_TEST_NODE_VERSION=8
services:
  - docker
