language: node_js
sudo: true
node_js:
  - "node"
  - "6"
  - "4"
  - "0.12"
  - "0.10"
before_install:
  - npm install -g npm@^3
before_script:
  - chmod -R 777 ./project/build/integration
env:
  - DOCKER_INTEGRATION_TEST_NODE_VERSION=6
services:
  - docker
